### PR TITLE
WIP: Update plugin to use chart.js v3

### PR DESCRIPTION
**Pull request by scottalan**
* This introduces a completely different build process using rollup
* WIP: Introduces typescript
* Chart.js has been updated from v2 -> v3

### CODE REVIEW

**Comment by scottalan** [comment]
Closing this until the PR is actually ready

**Comment by AYOKINYA** [comment]
Hi @scottalan 
Your code did help me to write text in the doughnut chart with chart.js 3.x. Thank you!
I know your PR is in progress, but just wanted to tell you
`const innerDiameter = chart.innerRadius * 2; ` at src/core.ts line 33 doesn't work as before.
Chart.js 3.x doesn't support chart.innerRadius. [chart.js issue page](https://github.com/chartjs/Chart.js/issues/7217)
`chart._metasets[chart._metasets.length-1].data[0].innerRadius` will do the chart.innerRadius of chart.js 2.x.
I'm looking forward to using your chartjs-plugin-doughnutlabel for Chart.js 3.x soon!

**Comment by koolkav1** [comment]
any update?

**Comment by choiip** [comment]
I found this [line of code](https://github.com/chartjs/Chart.js/blob/c057c96693819b41e7b89860f916c0aa361bafa5/src/elements/element.arc.js#L278) in chartjs repo. To get the innerRadius, 
```js
const datasetCount = chart.getVisibleDatasetCount();
const chartMeta = chart.getDatasetMeta(datasetCount-1).data.at(0);
if (chartMeta) {
	const {innerRadius} = chartMeta.getProps(['innerRadius']);
        ...
}

```
Hope this help.

**Comment by juanlet** [comment]
> I found this [line of code](https://github.com/chartjs/Chart.js/blob/c057c96693819b41e7b89860f916c0aa361bafa5/src/elements/element.arc.js#L278) in chartjs repo. To get the innerRadius,
> 
> ```js
> const datasetCount = chart.getVisibleDatasetCount();
> const chartMeta = chart.getDatasetMeta(datasetCount-1).data.at(0);
> if (chartMeta) {
> 	const {innerRadius} = chartMeta.getProps(['innerRadius']);
>         ...
> }
> ```
> 
> Hope this help.

Cool, that should be on the docs

**Comment by Demir-Utku** [comment]
Any improvements? Also, one should update the chart.js version to 4 in this PR

**Pull request closed without merging**
